# TODO 填写数据库连接信息
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  profiles:
    active: zty
  main:
    allow-circular-references: true
  application:
    name: kuangkuang

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${kuangkuang.datasource.host}:${kuangkuang.datasource.druid.port}/kuangkuang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${kuangkuang.datasource.username}
    password: ${kuangkuang.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${kuangkuang.datasource.host}:${kuangkuang.datasource.druid.port}/kuangkuang?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username:  ${kuangkuang.datasource.username}
      password:  ${kuangkuang.datasource.password}
  ai:
    ollama:
      base-url: http://${kuangkuang.host}:${kuangkuang.ai.port}
      chat:
        model: deepseek-r1:8b
    openai:
      api-key: ${kuangkuang.ai.openai.api-key}
  rabbitmq:
    host: ${kuangkuang.rabbitmq.host}
    port: ${kuangkuang.rabbitmq.port}
    username: ${kuangkuang.rabbitmq.username}
    password: ${kuangkuang.rabbitmq.password}
  # 邮件配置（敏感信息建议使用环境变量）
  mail:
    host:  ${kuangkuang.mail.host}
    username: ${kuangkuang.mail.username}
    password: ${kuangkuang.mail.password}
    from: ${kuangkuang.mail.from}
    from-name:  ${kuangkuang.mail.from-name}
    ssl:
      enabled: true
    port: ${kuangkuang.mail.port}
  data:
    redis:
      port: ${kuangkuang.data.redis.port}
      database: ${kuangkuang.data.redis.database}
      host: ${kuangkuang.data.redis.host}
xxl:
  job:
    executor:
      appname: kuangkuang
      logpath: kuangkuang/xxl-job
      logretentiondays: 3
      address:
      ip:
      port: 9999
      excludedpackage: org.springframework,spring
    admin:
      addresses: http://localhost:8081/xxl-job-admin
      accessToken: default_token
      timeout: 3



server:
  port: 8080
  address: 0.0.0.0


logging:
  level:
    com:
      xxl.job: debug
      xxl.job.core.thread.ExecutorRegistryThread: WARN
      kuangkuang:
        mapper: debug
        service: info
        controller: info
    org.springframework.ai.chat.client.advisor: debug
    org.springframework.jdbc: DEBUG





mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kuangkuang.kuangkuang.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


